export enum BoardMsg {
  Ping = 'pm_ping',
  Get = 'board_get',
  Aggregate = 'boards_aggregate',
  GetMy = 'board_get_my',
  GetAll = 'board_get_all',
  Create = 'board_create',
  Update = 'board_update',
  CreateColumns = 'board_create_columns',
  GetColumns = 'board_get_columns',
  AggregateColumns = 'board_aggregate_columns',
  CreateTask = 'board_task_create',
  MoveTask = 'board_move_task',
  AssignTask = 'board_assign_task',
  AddMembers = 'board_add_members',
  RemoveMembers = 'board_remove_members',
}
